# Generated by Django 4.2.11 on 2024-12-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'IN Review'), ('published', 'Published'), ('disabled', 'Disabled'), ('draft', 'Draft'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productsreviews',
            name='rating',
            field=models.ImageField(choices=[(5, '★★★★★'), (1, '★✩✩✩✩'), (4, '★★★★✩'), (3, '★★★✩✩'), (2, '★★✩✩✩')], default=None, upload_to=''),
        ),
    ]
